// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloWorldController from "./hello_world_controller"
application.register("hello-world", HelloWorldController)

import LayoutController from "./layout_controller"
application.register("layout", LayoutController)

import LoggerController from "./logger_controller"
application.register("logger", LoggerController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)
