// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormController from "./form_controller"
application.register("form", FormController)

import HelloWorldController from "./hello_world_controller"
application.register("hello-world", HelloWorldController)

import LoggerController from "./logger_controller"
application.register("logger", LoggerController)

import NavController from "./nav_controller"
application.register("nav", NavController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)
